import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import Header from './components/Header/Header.js';
import Footer from './components/Footer/Footer.js';
import { Toaster } from 'react-hot-toast';

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Casa do Kame',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={notoSansJp.className}>
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
        <Toaster position='top-right' />
      </body>
    </html>
  );
}
